Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,4 +21,10 @@ jobs:
       - name: Parameters check
         shell: bash
         run: | 
-          [[ ${{ inputs.vcluster_name }} =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]] && : || (echo "did not match"; exit 1)
+          if [[ ${#inputs.vcluster_name} -gt 10 ]] && [[ ${{ inputs.vcluster_name }} =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]]; then
+            :
+          else
+            echo -e "vcluster_name doesn't meet required crytiria. It must: \n-contain no more than 253 characters \n-contain only lowercase alphanumeric characters, '-' or '.' \n-start with an alphanumeric character \n-end with an alphanumeric characte"
+            exit 1
+          fi
+          
