Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,11 +21,21 @@ jobs:
       - name: Parameters check
         shell: bash
         run: | 
-          vcluster_name=${{ inputs.vcluster_name }}
-          if [[ ${#vcluster_name} -lt 10 ]] &&  [[ $vcluster_name =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]]; then
-            :
-          else
-            echo -e "vcluster_name doesn't meet required crytiria. It must: \n-contain no more than 253 characters \n-contain only lowercase alphanumeric characters, '-' or '.' \n-start with an alphanumeric character \n-end with an alphanumeric characte"
-            exit 1
-          fi
-          
+          # vcluster_name=${{ inputs.vcluster_name }}
+          # if [[ ${#vcluster_name} -lt 10 ]] &&  [[ $vcluster_name =~ ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ ]]; then
+          #   :
+          # else
+          #   echo -e "vcluster_name doesn't meet required crytiria. It must: \n-contain no more than 253 characters \n-contain only lowercase alphanumeric characters, '-' or '.' \n-start with an alphanumeric character \n-end with an alphanumeric characte"
+          #   exit 1
+          # fi
+  create-preview-env:
+    runs-on: ubuntu-latest
+    name: create-preview-env
+    steps:
+      - name: Parameters check
+        run: |
+          echo "vcluster_name=TEST_VCLUSTER" >> $GITHUB_ENV
+      - uses: ./.github/workflows/checks.yaml
+        name: create-preview-env
+        with:
+          vcluster_name: ${{ env.vcluster_name }}
